name: Cherry pick PR commits for label
on:
  pull_request_target:
    types: [closed]
jobs:
  cherry_pick_pr_for_label:
    name: Cherry pick PR commits for label
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: Cherry Pick PR for label
        uses: EventStore/Automations/cherry-pick-pr-for-label@cherry-pick-pr-for-label_ignore_for_not_merged
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
